// Euler Project Archives - ID:1 - Multiples of 3 or 5
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

// Find the sum of all the multiples of 3 or 5 below 1000.

import Foundation
import UIKit

func findThreeAndFive(x: Int, y: Int) -> Int{
    var sum: Int = 0
    var i: Int = 1
    while i < 1000{
        if i % x == 0 || i % y == 0{
            sum += i
        }
        i += 1
    }
    
    return sum
}

//var result: Int = findThreeAndFive(x: 3, y: 5)
//print(result)



// Euler Project Archives - ID:2 - Even Fibonacci numbers
/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

func sumEvenFiboNumbers() -> CLong{
    var x: CLong = 1
    var y: CLong = 1
    var sum: CLong = 0
    while y < 4000000{
        (x, y) = (y, x+y)
        
        if y % 2 == 0{
            sum += y
        }
    }
    return sum
}

//var sum: CLong = sumEvenFiboNumbers()
//print(sum)


// Euler Project Archives - ID:3 - Largest prime factor
/*
 The prime factors of 13195 are 5, 7, 13 and 29.

 What is the largest prime factor of the number 600851475143 ?
 */
// number.squareRoot()

func findMaxPrime(number: Int) -> Int{
    let number = number // 600851475143
    var i = 3
    var lastPrime: Int = 2
    while i < number / 2{
        var j = i - 1
        var isPrime = true
        while j >= 2{
            if i % j == 0{
                isPrime = false
                break
            }
            j -= 1
        }
        if isPrime{
            if number % i == 0{
                lastPrime = i
            }
            isPrime = false
        }
        i += 1
    }
    return lastPrime
}

var maxPrime: Int = findMaxPrime(number: 600851475143)
print(maxPrime)
